#:schema node_modules/wrangler/config-schema.json
name = "nexu"
compatibility_date = "2024-02-08"
compatibility_flags = ["nodejs_compat"]  # Add this line to enable Node.js compatibility

# Worker configuration
main = "_worker.js"

# Assets binding configuration - this is crucial
[build]
command = "" # Leave empty if no build step is needed
[build.upload]
format = "service-worker"

# This creates the ASSETS binding
[assets]
worker_compat = true
bucket = "./"

[build]
command = "npm install"

[build.upload]
external_node_modules = ["jsdom"]

[vars]
ENVIRONMENT = "production"

[observability.logs]
enabled = true



