#:schema node_modules/wrangler/config-schema.json
name = "nexu"
compatibility_date = "2024-02-08"
compatibility_flags = ["nodejs_compat"]  # Add this line to enable Node.js compatibility

# Worker configuration
main = "_worker.js"

[site]
bucket = "./"

[build]
command = "npm install"

[build.upload]
external_node_modules = ["jsdom"]

[vars]
ENVIRONMENT = "production"